# Generated by Django 6.0.4 on 2026-05-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=255)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
